/*
 * Convictional Interview API Contract
 *
 * This is the required output for the Convictional Eng Challenge
 *
 * API version: 1.0.0
 * Contact: samuel@convictional.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import (
	"time"
)

type Variant struct {
	ID        int64     `json:"id" bson:"id" binding:"required"`
	ProductID int64     `json:"product_id" bson:"product_id" binding:"required"`
	Title     string    `json:"title" bson:"title" binding:"required"`
	SKU       string    `json:"sku" bson:"sku" binding:"required"`
	Position  int64     `json:"position" bson:"position" binding:"required"`
	CreatedAt time.Time `json:"created_at" bson:"created_at" binding:"required"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at" binding:"required"`
	Taxable   bool      `json:"taxable" bson:"taxable" binding:"required"`
	Barcode   *[]byte   `json:"barcode" bson:"barcode" binding:",omitempty"`
	Grams     int64     `json:"grams" bson:"grams" binding:"required"`
	Weight    int64     `json:"weight" bson:"weight" binding:"required"`
	Price     Price     `json:"price" bson:"price" binding:"required"`
	Images    []Image   `json:"images" bson:"images" binding:",omitempty"`
}
